### ISSUE TITLE
One part of a page is in a smaller font than the other

### ISSUE THREAD

**Issue by lkintact** [ImageMagick/Usage#5]
At https://www.imagemagick.org/Usage/canvas/, starting with the text `gradient:angle=angle (in degrees)` the fontsize is smaller than above. That happens because of a `font-size:smaller !important;` inline rule in the containing `<div>`, and is probably wrong.

**Comment by dlemstra** [comment]
Closing this as this looks to be intended. The table is shown in a smaller font.

**Comment by lkintact** [comment]
> The table is shown in a smaller font.

Not just the table - all the text all the way down to the end of the page.

Perhaps clicking on this link:
https://www.imagemagick.org/Usage/canvas/#gradient
and then on this:
https://www.imagemagick.org/Usage/canvas/#radial-gradient
will be illustrative.

**Comment by dlemstra** [comment]
I misunderstood your message. Turns out the `div` was closed at the wrong spot. I pushed a patch to fix this.
